### ISSUE TITLE
Confirm when save file is going to be overwritten

### ISSUE THREAD

**Issue by hhaslam11** [hhaslam11/Text-Fighter#63]
New Game --> Enter existing save file

**Comment by hhaslam11** [comment]
that sounds awesome! Seems good to me :) let me know if you run into any issues; I've also learned a lot since I was actively working on this and I'm actually working as a full-time Java engineer now haha

**Comment by BrendonButler** [comment]
Implemented saving feature that will automatically append a number to save files to prevent duplicate usernames overwriting an existing save. Usernames are also stored within the save file so they're _technically_ modifiable. This allows for more dynamic loading by giving you a selection of saving files to load instead of asking for the specific username to load. Another change in PR #143 related to this issue is that the save file naming scheme has been simplified. Instead of "Text-Fighter_USERNAME.TFsave", it's now simply, "USERNAME.TFsave".

EX: If there was a file "Brendon.TFsave" and you created a new game with the username "Brendon," it would automatically save this new game as "Brendon (1).TFsave". Incrementing the number every time a game is made with that same username.
